/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.Main;

import br.com.Dao.clienteDao;
import br.com.Dao.planoDao;
import br.com.Dao.usuarioDao;
import br.com.Modelo.Cliente;
import br.com.Modelo.Planobean;
import br.com.Modelo.Usuariobean;
import br.com.utilitarios.CustomTableCellRenderer;
import br.com.utilitarios.CustomTableCellRendererPlano;
import br.com.utilitarios.CustomTableCellRendererUsuario;
import br.com.views.Plano;
import br.com.views.Usuario;
import br.com.views.clientes;
import static com.alee.extended.time.ClockType.timer;
import com.alee.laf.WebLookAndFeel;
import com.alee.laf.optionpane.WebOptionPane;
import de.javasoft.plaf.synthetica.SyntheticaBlackEyeLookAndFeel;
import de.javasoft.plaf.synthetica.SyntheticaBlackMoonLookAndFeel;
import de.javasoft.plaf.synthetica.SyntheticaSilverMoonLookAndFeel;
import de.javasoft.plaf.synthetica.SyntheticaStandardLookAndFeel;
//import de.javasoft.plaf.synthetica.SyntheticaWhiteVisionLookAndFeel;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Iterator;
import java.util.List;
import javax.swing.JDialog;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author marcos
 */
public class principal extends javax.swing.JFrame implements ActionListener {

    /**
     * Creates new form principal
     */
    TableColumn tcol;
    JPopupMenu jPopupMenu;
    JMenuItem jMenuItemAlterar;

    JPopupMenu jPopupMenuPlano;
    JMenuItem jMenuItemAlterarPlano;

    JPopupMenu jPopupMenuUsuario;
    JMenuItem jMenuItemAlterarUsuario;

    private javax.swing.Timer timer;

    public principal() {
        initComponents();
        jPopupMenu = new JPopupMenu();
        jMenuItemAlterar = new JMenuItem();
        jMenuItemAlterar.setText("Alterar");

        jPopupMenuPlano = new JPopupMenu();
        jMenuItemAlterarPlano = new JMenuItem();
        jMenuItemAlterarPlano.setText("Alterar");

        jPopupMenuUsuario = new JPopupMenu();
        jMenuItemAlterarUsuario = new JMenuItem();
        jMenuItemAlterarUsuario.setText("Alterar");

        disparaRelogio();
        popUpTableCliente();
        popUpTablePlano();
        popUpTableUsuario();
        carregarTabelaCliente();
        carregarTabelaPlano();
        carregarTabelaUsuario();
        this.setExtendedState(this.MAXIMIZED_BOTH);
    }

    public principal(Usuariobean usuario , int autenticacao) {
        initComponents();
        if(autenticacao == 1){
        
             this.bt_cadastroUsuario.setEnabled(false);
             this.bt_editarUsuario.setEnabled(false);
             this.panelUsuario.setEnabled(false);
             this.btn_excluirUsuario.setEnabled(false);
        
        }
      
        jPopupMenu = new JPopupMenu();
        jMenuItemAlterar = new JMenuItem();
        jMenuItemAlterar.setText("Alterar");

        jPopupMenuPlano = new JPopupMenu();
        jMenuItemAlterarPlano = new JMenuItem();
        jMenuItemAlterarPlano.setText("Alterar");

        jPopupMenuUsuario = new JPopupMenu();
       jMenuItemAlterarUsuario = new JMenuItem();
        jMenuItemAlterarUsuario.setText("Alterar");

        disparaRelogio();
        popUpTableCliente();
        popUpTablePlano();
      //  popUpTableUsuario();
        carregarTabelaCliente();
        carregarTabelaPlano();
        carregarTabelaUsuario();
        this.setExtendedState(this.MAXIMIZED_BOTH);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel10 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_cliente = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        bt_editarCliente = new javax.swing.JButton();
        btn_excluirCliente = new javax.swing.JButton();
        bt_cadastroCliente = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jTextField1 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        btn_excluir1 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jTextField2 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        btn_editarPlano = new javax.swing.JButton();
        btn_excluirPlano = new javax.swing.JButton();
        btn_novoPlano = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jTextField3 = new javax.swing.JTextField();
        jButton9 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb_plano = new javax.swing.JTable();
        panelUsuario = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        bt_editarUsuario = new javax.swing.JButton();
        btn_excluirUsuario = new javax.swing.JButton();
        bt_cadastroUsuario = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        jTextField4 = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tb_usuario = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(4, 0), new java.awt.Dimension(4, 0), new java.awt.Dimension(4, 32767));
        lb_horas = new javax.swing.JLabel();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lb_data = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jPanel11 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane4.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        jPanel10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        tb_cliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nome", "Email", "CPF", "RG", "Situacão"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tb_cliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_clienteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_cliente);

        bt_editarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/Imagens/Modify.png"))); // NOI18N
        bt_editarCliente.setText("Editar");
        bt_editarCliente.setFocusable(false);
        bt_editarCliente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_editarCliente.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bt_editarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_editarClienteActionPerformed(evt);
            }
        });

        btn_excluirCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/Imagens/Delete_32x32.png"))); // NOI18N
        btn_excluirCliente.setText("Excluir");
        btn_excluirCliente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_excluirCliente.setVerifyInputWhenFocusTarget(false);
        btn_excluirCliente.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_excluirCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_excluirClienteActionPerformed(evt);
            }
        });

        bt_cadastroCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/Imagens/Profile.png"))); // NOI18N
        bt_cadastroCliente.setText("Cadastro");
        bt_cadastroCliente.setFocusable(false);
        bt_cadastroCliente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_cadastroCliente.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bt_cadastroCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cadastroClienteActionPerformed(evt);
            }
        });

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/Imagens/Search.png"))); // NOI18N
        jButton4.setText("Pesquisar");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(bt_cadastroCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_editarCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_excluirCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btn_excluirCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_editarCliente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_cadastroCliente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4))
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1091, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Cliente", jPanel2);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/Imagens/Modify.png"))); // NOI18N
        jButton3.setText("Editar");
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        btn_excluir1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/Imagens/Delete_32x32.png"))); // NOI18N
        btn_excluir1.setText("Excluir");
        btn_excluir1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_excluir1.setVerifyInputWhenFocusTarget(false);
        btn_excluir1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_excluir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_excluir1ActionPerformed(evt);
            }
        });

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/Imagens/Profile.png"))); // NOI18N
        jButton5.setText("Cadastro");
        jButton5.setFocusable(false);
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/Imagens/Search.png"))); // NOI18N
        jButton6.setText("Pesquisar");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_excluir1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btn_excluir1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6))
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 296, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Financeiro", jPanel3);

        btn_editarPlano.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/Imagens/Modify.png"))); // NOI18N
        btn_editarPlano.setText("Editar");
        btn_editarPlano.setFocusable(false);
        btn_editarPlano.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_editarPlano.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_editarPlano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editarPlanoActionPerformed(evt);
            }
        });

        btn_excluirPlano.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/Imagens/Delete_32x32.png"))); // NOI18N
        btn_excluirPlano.setText("Excluir");
        btn_excluirPlano.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_excluirPlano.setVerifyInputWhenFocusTarget(false);
        btn_excluirPlano.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_excluirPlano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_excluirPlanoActionPerformed(evt);
            }
        });

        btn_novoPlano.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/Imagens/Add.png"))); // NOI18N
        btn_novoPlano.setText("Novo Plano");
        btn_novoPlano.setFocusable(false);
        btn_novoPlano.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_novoPlano.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_novoPlano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_novoPlanoActionPerformed(evt);
            }
        });

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/Imagens/Search.png"))); // NOI18N
        jButton9.setText("Pesquisar");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(btn_novoPlano)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_editarPlano)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_excluirPlano, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton9)
                .addContainerGap(357, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator3)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btn_excluirPlano, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_editarPlano, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_novoPlano, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton9))
                .addGap(24, 24, 24))
        );

        tb_plano.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Plano", "Valor", "qtd. Meses"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tb_plano.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_planoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tb_plano);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane2)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Plano", jPanel5);

        bt_editarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/Imagens/Modify.png"))); // NOI18N
        bt_editarUsuario.setText("Editar");
        bt_editarUsuario.setFocusable(false);
        bt_editarUsuario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_editarUsuario.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bt_editarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_editarUsuarioActionPerformed(evt);
            }
        });

        btn_excluirUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/Imagens/Delete_32x32.png"))); // NOI18N
        btn_excluirUsuario.setText("Excluir");
        btn_excluirUsuario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_excluirUsuario.setVerifyInputWhenFocusTarget(false);
        btn_excluirUsuario.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_excluirUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_excluirUsuarioActionPerformed(evt);
            }
        });

        bt_cadastroUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/Imagens/User_32x32.png"))); // NOI18N
        bt_cadastroUsuario.setText("Cadastro");
        bt_cadastroUsuario.setFocusable(false);
        bt_cadastroUsuario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_cadastroUsuario.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bt_cadastroUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cadastroUsuarioActionPerformed(evt);
            }
        });

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/Imagens/Search.png"))); // NOI18N
        jButton7.setText("Pesquisar");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(bt_cadastroUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_editarUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_excluirUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton7)
                .addContainerGap(375, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator4)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btn_excluirUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_editarUsuario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_cadastroUsuario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7))
                .addGap(24, 24, 24))
        );

        tb_usuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Usuario", "Senha", "Autenticação"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tb_usuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_usuarioMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tb_usuario);

        javax.swing.GroupLayout panelUsuarioLayout = new javax.swing.GroupLayout(panelUsuario);
        panelUsuario.setLayout(panelUsuarioLayout);
        panelUsuarioLayout.setHorizontalGroup(
            panelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane3)
        );
        panelUsuarioLayout.setVerticalGroup(
            panelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUsuarioLayout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Usuario", panelUsuario);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1))
        );

        jPanel1.setBackground(new java.awt.Color(46, 46, 46));

        jLabel1.setBackground(new java.awt.Color(253, 136, 18));
        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(43, 121, 212));
        jLabel1.setText(" Sisclinica 1.0    ");
        jLabel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 2, 0, 2));

        lb_horas.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        lb_horas.setForeground(new java.awt.Color(241, 241, 241));
        lb_horas.setText(" 13:45:00");

        filler2.setBackground(new java.awt.Color(162, 7, 7));

        jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(239, 89, 101));
        jLabel3.setText("Usuario :");

        jLabel4.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(254, 254, 254));
        jLabel4.setText("marcosvto");

        jLabel5.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(239, 89, 101));
        jLabel5.setText("Tipo : ");

        jLabel6.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(254, 254, 254));
        jLabel6.setText("Administrador");

        jLabel7.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(239, 89, 101));
        jLabel7.setText("Data :");

        lb_data.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        lb_data.setForeground(new java.awt.Color(244, 244, 244));
        lb_data.setText("jLabel2");

        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator6.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator7.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(9, 9, 9)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(65, 65, 65)
                .addComponent(filler2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(105, 105, 105)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lb_data)
                .addGap(23, 23, 23)
                .addComponent(lb_horas)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(filler2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(filler1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lb_data, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lb_horas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator5)
            .addComponent(jSeparator6)
            .addComponent(jSeparator7)
        );

        jPanel11.setBackground(new java.awt.Color(79, 78, 78));
        jPanel11.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 2, 0));

        jButton1.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jButton1.setForeground(new java.awt.Color(239, 89, 101));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/Imagens/Log Out_32x32.png"))); // NOI18N
        jButton1.setText("Sair  ");
        jButton1.setBorderPainted(false);
        jButton1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void carregarTabelaCliente() {
        tb_cliente.getColumnModel().getColumn(0).setCellRenderer(new CustomTableCellRenderer());
        tb_cliente.getColumnModel().getColumn(1).setCellRenderer(new CustomTableCellRenderer());
        tb_cliente.getColumnModel().getColumn(2).setCellRenderer(new CustomTableCellRenderer());
        tb_cliente.getColumnModel().getColumn(3).setCellRenderer(new CustomTableCellRenderer());
        tb_cliente.getColumnModel().getColumn(4).setCellRenderer(new CustomTableCellRenderer());
        tb_cliente.getColumnModel().getColumn(5).setCellRenderer(new CustomTableCellRenderer());

    }

    private void carregarTabelaPlano() {

        tb_plano.getColumnModel().getColumn(0).setCellRenderer(new CustomTableCellRendererPlano());
        tb_plano.getColumnModel().getColumn(1).setCellRenderer(new CustomTableCellRendererPlano());
        tb_plano.getColumnModel().getColumn(2).setCellRenderer(new CustomTableCellRendererPlano());
        tb_plano.getColumnModel().getColumn(3).setCellRenderer(new CustomTableCellRendererPlano());

    }

    private void carregarTabelaUsuario() {

        tb_usuario.getColumnModel().getColumn(0).setCellRenderer(new CustomTableCellRendererUsuario());
        tb_usuario.getColumnModel().getColumn(1).setCellRenderer(new CustomTableCellRendererUsuario());
        tb_usuario.getColumnModel().getColumn(2).setCellRenderer(new CustomTableCellRendererUsuario());
        tb_usuario.getColumnModel().getColumn(3).setCellRenderer(new CustomTableCellRendererUsuario());

    }
    //horas do sistema atual 
    public void actionPerformed(ActionEvent ae) {
        Date hora = new Date();
        Date data = new Date();
        SimpleDateFormat hora_formato = new SimpleDateFormat("HH:mm:ss");
        SimpleDateFormat data_formato = new SimpleDateFormat("dd/MM/yyyy");
        lb_horas.setText(hora_formato.format(hora));
        lb_data.setText(data_formato.format(data));

    }

    public void disparaRelogio() {
        if (timer == null) {
            timer = new javax.swing.Timer(1000, this);
            timer.setInitialDelay(0);
            timer.start();
        } else if (!timer.isRunning()) {
            timer.restart();
        }
    }

    private void bt_cadastroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cadastroClienteActionPerformed
        // TODO add your handling code here:
        //cliente PanelCliente = new cliente();
        //PanelCliente.setSize(780, 500);
        // PanelCliente.carregarCliente();
        clientes dia = new clientes(null, true);
        dia.setSize(780, 500);
        dia.setModal(true);
        dia.pack();
        //dia.getDefaultCloseOperation();        
        dia.setLocationRelativeTo(null);
        dia.setVisible(true);
    }//GEN-LAST:event_bt_cadastroClienteActionPerformed
    //evento de abertura do windows
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        this.setFocusable(true);
        carregarCliente();
        carregarPlano();
        carregarUsuario();
    }//GEN-LAST:event_formWindowOpened
    //evento de ativaçao do windwos
    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        if (tb_cliente.getRowCount() >= 0) {

            removerall(tb_cliente);
            carregarCliente();

        } else {
            //    carregarCliente();
        }

        if (tb_plano.getRowCount() >= 0) {

            removerall(tb_plano);
            carregarPlano();

        } else {
            //    carregarCliente();
        }

        if (tb_usuario.getRowCount() >= 0) {

            removerall(tb_usuario);
            carregarUsuario();

        } else {
            //    carregarCliente();
        }

    }//GEN-LAST:event_formWindowActivated

    private void btn_excluirClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_excluirClienteActionPerformed
        // TODO add your handling code here:
        if (tb_cliente.getSelectedRow() == -1) {

            JOptionPane.showMessageDialog(null, "Selecione um cliente !!");
        }
    }//GEN-LAST:event_btn_excluirClienteActionPerformed

    private void bt_editarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_editarClienteActionPerformed
        // TODO add your handling code here:
        if (tb_cliente.getSelectedRow() == -1) {

            JOptionPane.showMessageDialog(null, "Selecione um cliente !!");
        } else {

            clientes dia = new clientes(null, true, dadosCliente());
            dia.setSize(780, 500);
            dia.setModal(true);
            dia.pack();
            dia.getDefaultCloseOperation();
            dia.setLocationRelativeTo(null);
            dia.setVisible(true);

        }
    }//GEN-LAST:event_bt_editarClienteActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btn_excluir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_excluir1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_excluir1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void btn_editarPlanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editarPlanoActionPerformed
        // TODO add your handling code here:
        if (tb_plano.getSelectedRow() == -1) {

            JOptionPane.showMessageDialog(null, "Selecione um plano !!");
        } else {

            Plano dia = new Plano(null, true, dadosPlano());
            dia.setSize(780, 500);
            dia.setModal(true);
            dia.pack();
            dia.getDefaultCloseOperation();
            dia.setLocationRelativeTo(null);
            dia.setVisible(true);

        }

    }//GEN-LAST:event_btn_editarPlanoActionPerformed

    private void btn_excluirPlanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_excluirPlanoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_excluirPlanoActionPerformed
    private void btn_novoPlanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_novoPlanoActionPerformed
        // TODO add your handling code here:
        Plano dia = new Plano(null, true);
        dia.setSize(500, 400);
        dia.setModal(true);
        dia.pack();
        dia.getDefaultCloseOperation();
        dia.setLocationRelativeTo(null);
        dia.setVisible(true);
    }//GEN-LAST:event_btn_novoPlanoActionPerformed

    private void tb_clienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_clienteMouseClicked
        // TODO add your handling code here:
        if (tb_cliente.getSelectedRow() != -1) {
            if (evt.getButton() == java.awt.event.MouseEvent.BUTTON3) {

                jPopupMenu.show(tb_cliente, evt.getX(), evt.getY());
            }
        }
    }//GEN-LAST:event_tb_clienteMouseClicked

    private void bt_editarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_editarUsuarioActionPerformed
        // TODO add your handling code here:
        if (tb_usuario.getSelectedRow() == -1) {

            JOptionPane.showMessageDialog(null, "Selecione um Usuario !!");
        } else {

            Usuario dia = new Usuario(null, true, dadosUsuario());
            dia.setSize(425, 210);
            dia.setModal(true);
            dia.pack();
            dia.getDefaultCloseOperation();
            dia.setLocationRelativeTo(null);
            dia.setVisible(true);

        }

    }//GEN-LAST:event_bt_editarUsuarioActionPerformed

    private void btn_excluirUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_excluirUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_excluirUsuarioActionPerformed

    private void bt_cadastroUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cadastroUsuarioActionPerformed
        // TODO add your handling code here:
        Usuario dia = new Usuario(null, true);
        dia.setSize(425, 210);
        dia.setModal(true);
        dia.pack();
        //dia.getDefaultCloseOperation();        
        dia.setLocationRelativeTo(null);
        dia.setVisible(true);


    }//GEN-LAST:event_bt_cadastroUsuarioActionPerformed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed

        if (evt.getKeyCode() == 27) {

            int opc = WebOptionPane.showConfirmDialog(this, "Deseja Sair Realmente?", "Confirmação",
                    WebOptionPane.YES_NO_OPTION, WebOptionPane.QUESTION_MESSAGE);
            if (opc == 0) {

                this.dispose();
                System.exit(0);
            }
        }
    }//GEN-LAST:event_formKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int opc = WebOptionPane.showConfirmDialog(this, "Deseja Sair Realmente?", "Confirmação",
                WebOptionPane.YES_NO_OPTION, WebOptionPane.QUESTION_MESSAGE);
        if (opc == 0) {

            this.dispose();
            System.exit(0);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tb_planoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_planoMouseClicked
        // TODO add your handling code here:
        if (tb_plano.getSelectedRow() != -1) {
            if (evt.getButton() == java.awt.event.MouseEvent.BUTTON3) {

                jPopupMenuPlano.show(tb_plano, evt.getX(), evt.getY());
            }
        }
    }//GEN-LAST:event_tb_planoMouseClicked

    private void tb_usuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_usuarioMouseClicked
        // TODO add your handling code here:
        if (tb_usuario.getSelectedRow() != -1) {
            if (evt.getButton() == java.awt.event.MouseEvent.BUTTON3) {

                jPopupMenuUsuario.show(tb_usuario, evt.getX(), evt.getY());
            }
        }
    }//GEN-LAST:event_tb_usuarioMouseClicked

    public Cliente dadosCliente() {
        Cliente dcliente = new Cliente();
        int linhaSelecionada = tb_cliente.getSelectedRow();
        dcliente.setId(Integer.parseInt(tb_cliente.getValueAt(linhaSelecionada, 0).toString()));
        dcliente.setNome(tb_cliente.getValueAt(linhaSelecionada, 1).toString());
        dcliente.setEmail(tb_cliente.getValueAt(linhaSelecionada, 2).toString());
        dcliente.setCpf(tb_cliente.getValueAt(linhaSelecionada, 3).toString());
        dcliente.setRg(tb_cliente.getValueAt(linhaSelecionada, 4).toString());
        dcliente.setSituacao(tb_cliente.getValueAt(linhaSelecionada, 5).toString());
        return dcliente;
    }

    public Planobean dadosPlano() {
        Planobean dplano = new Planobean();
        int linhaSelecionada = tb_plano.getSelectedRow();
        dplano.setId(Integer.parseInt(tb_plano.getValueAt(linhaSelecionada, 0).toString()));
        dplano.setNome(tb_plano.getValueAt(linhaSelecionada, 1).toString());
        dplano.setValor(Double.parseDouble(tb_plano.getValueAt(linhaSelecionada, 2).toString()));
        dplano.setQuantidadeMeses(Integer.parseInt(tb_plano.getValueAt(linhaSelecionada, 3).toString()));

        return dplano;
    }

    public Usuariobean dadosUsuario() {
        Usuariobean dusuario = new Usuariobean();
        int linhaSelecionada = tb_usuario.getSelectedRow();
        dusuario.setId(Integer.parseInt(tb_usuario.getValueAt(linhaSelecionada, 0).toString()));
        dusuario.setUsuario(tb_usuario.getValueAt(linhaSelecionada, 1).toString());
        dusuario.setSenha(tb_usuario.getValueAt(linhaSelecionada, 2).toString());
        int p = ((tb_usuario.getValueAt(linhaSelecionada, 3).toString()).equalsIgnoreCase("Administrador")) ? 1 : 2;
        dusuario.setAutentica(p);

        return dusuario;
    }

    public void removerall(JTable tb) {

        DefaultTableModel model = (DefaultTableModel) tb.getModel();
        int cont = tb.getRowCount();
        for (int i = 1; i <= cont; i++) {

            model.removeRow(0);
        }
    }

    private void popUpTableCliente() {

        jMenuItemAlterar.addActionListener(
                new java.awt.event.ActionListener() {
                    // Importe a classe java.awt.event.ActionEvent  
                    public void actionPerformed(ActionEvent e) {
                        int index = tb_cliente.getSelectedRow();
                        // Faça alguma coisa com o item selecionado  
                        clientes dia = new clientes(null, true, dadosCliente());
                        dia.setSize(780, 500);
                        dia.setModal(true);
                        dia.pack();
                        dia.getDefaultCloseOperation();
                        dia.setLocationRelativeTo(null);
                        dia.setVisible(true);
                    }

                });

        JMenuItem jMenuItemExcluir = new JMenuItem();
        jMenuItemExcluir.setText("Excluir");
        jMenuItemExcluir.addActionListener(
                new java.awt.event.ActionListener() {
                    // Importe a classe java.awt.event.ActionEvent  
                    public void actionPerformed(ActionEvent e) {
                        int index = tb_cliente.getSelectedRow();
                        // Faça alguma coisa com o item selecionado  
                        JOptionPane.showMessageDialog(null, "Oloco meu , funciona memso");
                    }
                });

        jPopupMenu.add(jMenuItemAlterar);
        jPopupMenu.add(jMenuItemExcluir);

    }

    private void popUpTablePlano() {

        jMenuItemAlterarPlano.addActionListener(
                new java.awt.event.ActionListener() {
                    // Importe a classe java.awt.event.ActionEvent  
                    public void actionPerformed(ActionEvent e) {
                        int index = tb_plano.getSelectedRow();
                        // Faça alguma coisa com o item selecionado  
                  
                        Plano dia = new Plano(null, true, dadosPlano());
                        dia.setSize(500, 400);
                        dia.setModal(true);
                        dia.pack();
                        dia.getDefaultCloseOperation();
                        dia.setLocationRelativeTo(null);
                        dia.setVisible(true);
                    }

                });

        JMenuItem jMenuItemExcluir = new JMenuItem();
        jMenuItemExcluir.setText("Excluir");
        jMenuItemExcluir.addActionListener(
                new java.awt.event.ActionListener() {
                    // Importe a classe java.awt.event.ActionEvent  
                    public void actionPerformed(ActionEvent e) {
                        int index = tb_plano.getSelectedRow();
                        // Faça alguma coisa com o item selecionado  
                        JOptionPane.showMessageDialog(null, "Oloco meu , funciona memso");
                    }
                });

        jPopupMenuPlano.add(jMenuItemAlterarPlano);
        jPopupMenuPlano.add(jMenuItemExcluir);

    }

    private void popUpTableUsuario() {

        jMenuItemAlterarUsuario.addActionListener(
                new java.awt.event.ActionListener() {
                    // Importe a classe java.awt.event.ActionEvent  
                    public void actionPerformed(ActionEvent e) {
                        int index = tb_usuario.getSelectedRow();
                        // Faça alguma coisa com o item selecionado  
                        Usuario dia = new Usuario(null, true, dadosUsuario());
                        dia.setSize(780, 500);
                        dia.setModal(true);
                        dia.pack();
                        dia.getDefaultCloseOperation();
                        dia.setLocationRelativeTo(null);
                        dia.setVisible(true);
                    }

                });

        JMenuItem jMenuItemExcluir = new JMenuItem();
        jMenuItemExcluir.setText("Excluir");
        jMenuItemExcluir.addActionListener(
                new java.awt.event.ActionListener() {
                    // Importe a classe java.awt.event.ActionEvent  
                    public void actionPerformed(ActionEvent e) {
                        int index = tb_usuario.getSelectedRow();
                        // Faça alguma coisa com o item selecionado  
                        JOptionPane.showMessageDialog(null, "Oloco meu , funciona memso");
                    }
                });

        jPopupMenuUsuario.add(jMenuItemAlterarUsuario);
        jPopupMenuUsuario.add(jMenuItemExcluir);

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws ParseException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            /* for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
             if ("Nimbus".equals(info.getName())) {
             javax.swing.UIManager.setLookAndFeel(info.getClassName());
             break;
             }
             }*/
            javax.swing.UIManager.setLookAndFeel(new WebLookAndFeel());
            //       javax.swing.UIManager.setLookAndFeel(new SyntheticaWhiteVisionLookAndFeel());
            //  javax.swing.UIManager.setLookAndFeel(new SyntheticaStandardLookAndFeel());

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new principal().setVisible(true);
            }
        });
    }

    public void carregarCliente() {
        DefaultTableModel model = (DefaultTableModel) tb_cliente.getModel();
        clienteDao dao = new clienteDao();
        Object[] cli = new Object[5];
        Iterator ita = dao.getLista().iterator();

        List<Cliente> clientes = dao.getLista();

        for (Cliente cliente : clientes) {

            model.addRow(new Object[]{cliente.getId(), cliente.getNome(), cliente.getEmail(), cliente.getCpf(), cliente.getRg(), cliente.getSituacao()});

        }

        /* while(ita.hasNext()){
              
         ArrayList<Cliente> c = (ArrayList) ita.next();
         cli[1] = c.get(WIDTH).
             
         }*/
    }

    public void carregarPlano() {
        DefaultTableModel model = (DefaultTableModel) tb_plano.getModel();
        planoDao dao = new planoDao();
        Object[] cli = new Object[5];
        Iterator ita = dao.getLista().iterator();

        List<Planobean> planos = dao.getLista();

        for (Planobean plano : planos) {

            model.addRow(new Object[]{plano.getId(), plano.getNome(), plano.getValor(), plano.getQuantidadeMeses()});

        }

        /* while(ita.hasNext()){
              
         ArrayList<Cliente> c = (ArrayList) ita.next();
         cli[1] = c.get(WIDTH).
             
         }*/
    }

    public void carregarUsuario() {
        DefaultTableModel model = (DefaultTableModel) tb_usuario.getModel();
        usuarioDao dao = new usuarioDao();
        Object[] cli = new Object[5];
        Iterator ita = dao.getLista().iterator();
        String auto;

        List<Usuariobean> usuarios = dao.getLista();

        for (Usuariobean usuario : usuarios) {

            int autentica = usuario.getAutentica();
            auto = (autentica == 1) ? "Administrador" : "Funcionario";

            model.addRow(new Object[]{usuario.getId(), usuario.getUsuario(), usuario.getSenha(), auto});

        }

        /* while(ita.hasNext()){
              
         ArrayList<Cliente> c = (ArrayList) ita.next();
         cli[1] = c.get(WIDTH).
             
         }*/
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_cadastroCliente;
    private javax.swing.JButton bt_cadastroUsuario;
    private javax.swing.JButton bt_editarCliente;
    private javax.swing.JButton bt_editarUsuario;
    private javax.swing.JButton btn_editarPlano;
    private javax.swing.JButton btn_excluir1;
    private javax.swing.JButton btn_excluirCliente;
    private javax.swing.JButton btn_excluirPlano;
    private javax.swing.JButton btn_excluirUsuario;
    private javax.swing.JButton btn_novoPlano;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JLabel lb_data;
    private javax.swing.JLabel lb_horas;
    private javax.swing.JPanel panelUsuario;
    private javax.swing.JTable tb_cliente;
    private javax.swing.JTable tb_plano;
    private javax.swing.JTable tb_usuario;
    // End of variables declaration//GEN-END:variables

}
